local: &local
  movie_service_url: 'https://api.themoviedb.org'
  movie_service_api_key: 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0ZWRhZTU4MGVlOGUxNjJkZjJlZGZjMDZkZGI5OWJhYSIsIm5iZiI6MTc0MTgwMDEwOC4zODIwMDAyLCJzdWIiOiI2N2QxYzJhYzQyYzBjY2MzY2ExZTNkZWEiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.T_wC7nyZ-z02RPi1qvz1SzCan6CW704ck0dRREX3mQs'

remote: &remote
  movie_service_url: "<%= ENV['MOVIE_SERVICE_URL'] %>"
  movie_service_url: "<%= ENV['MOVIE_SERVICE_API_KEY'] %>"

development:
  <<: *local

test:
  <<: *local

staging:
  <<: *remote

production:
  <<: *remote
